// Generated by gencpp from file sb_msgs/CarCommand.msg
// DO NOT EDIT!


#ifndef SB_MSGS_MESSAGE_CARCOMMAND_H
#define SB_MSGS_MESSAGE_CARCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sb_msgs
{
template <class ContainerAllocator>
struct CarCommand_
{
  typedef CarCommand_<ContainerAllocator> Type;

  CarCommand_()
    : throttle(0.0)
    , steering(0.0)
    , priority(0.0)  {
    }
  CarCommand_(const ContainerAllocator& _alloc)
    : throttle(0.0)
    , steering(0.0)
    , priority(0.0)  {
    }



   typedef double _throttle_type;
  _throttle_type throttle;

   typedef double _steering_type;
  _steering_type steering;

   typedef double _priority_type;
  _priority_type priority;




  typedef boost::shared_ptr< ::sb_msgs::CarCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sb_msgs::CarCommand_<ContainerAllocator> const> ConstPtr;

}; // struct CarCommand_

typedef ::sb_msgs::CarCommand_<std::allocator<void> > CarCommand;

typedef boost::shared_ptr< ::sb_msgs::CarCommand > CarCommandPtr;
typedef boost::shared_ptr< ::sb_msgs::CarCommand const> CarCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sb_msgs::CarCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sb_msgs::CarCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sb_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sb_msgs': ['/home/dulluhan/Desktop/ROS_GPS/src/sb_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sb_msgs::CarCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sb_msgs::CarCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sb_msgs::CarCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sb_msgs::CarCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sb_msgs::CarCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sb_msgs::CarCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sb_msgs::CarCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c31a3d204e29a9c88edbb8e52ee6bad6";
  }

  static const char* value(const ::sb_msgs::CarCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc31a3d204e29a9c8ULL;
  static const uint64_t static_value2 = 0x8edbb8e52ee6bad6ULL;
};

template<class ContainerAllocator>
struct DataType< ::sb_msgs::CarCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sb_msgs/CarCommand";
  }

  static const char* value(const ::sb_msgs::CarCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sb_msgs::CarCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Car command that arduinoDriver or furiousDriver can understand\n\
\n\
float64 throttle # throttle value -1 < x < 1\n\
float64 steering # steering value -1 < x < 1\n\
float64 priority # priority value  0 < x < 1\n\
";
  }

  static const char* value(const ::sb_msgs::CarCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sb_msgs::CarCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.throttle);
      stream.next(m.steering);
      stream.next(m.priority);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct CarCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sb_msgs::CarCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sb_msgs::CarCommand_<ContainerAllocator>& v)
  {
    s << indent << "throttle: ";
    Printer<double>::stream(s, indent + "  ", v.throttle);
    s << indent << "steering: ";
    Printer<double>::stream(s, indent + "  ", v.steering);
    s << indent << "priority: ";
    Printer<double>::stream(s, indent + "  ", v.priority);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SB_MSGS_MESSAGE_CARCOMMAND_H
