// Generated by gencpp from file sb_msgs/IMU.msg
// DO NOT EDIT!


#ifndef SB_MSGS_MESSAGE_IMU_H
#define SB_MSGS_MESSAGE_IMU_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sb_msgs
{
template <class ContainerAllocator>
struct IMU_
{
  typedef IMU_<ContainerAllocator> Type;

  IMU_()
    : c_x(0)
    , c_y(0)
    , c_z(0)
    , a_x(0)
    , a_y(0)
    , a_z(0)
    , g_x(0)
    , g_y(0)
    , g_z(0)  {
    }
  IMU_(const ContainerAllocator& _alloc)
    : c_x(0)
    , c_y(0)
    , c_z(0)
    , a_x(0)
    , a_y(0)
    , a_z(0)
    , g_x(0)
    , g_y(0)
    , g_z(0)  {
    }



   typedef int32_t _c_x_type;
  _c_x_type c_x;

   typedef int32_t _c_y_type;
  _c_y_type c_y;

   typedef int32_t _c_z_type;
  _c_z_type c_z;

   typedef int32_t _a_x_type;
  _a_x_type a_x;

   typedef int32_t _a_y_type;
  _a_y_type a_y;

   typedef int32_t _a_z_type;
  _a_z_type a_z;

   typedef int32_t _g_x_type;
  _g_x_type g_x;

   typedef int32_t _g_y_type;
  _g_y_type g_y;

   typedef int32_t _g_z_type;
  _g_z_type g_z;




  typedef boost::shared_ptr< ::sb_msgs::IMU_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sb_msgs::IMU_<ContainerAllocator> const> ConstPtr;

}; // struct IMU_

typedef ::sb_msgs::IMU_<std::allocator<void> > IMU;

typedef boost::shared_ptr< ::sb_msgs::IMU > IMUPtr;
typedef boost::shared_ptr< ::sb_msgs::IMU const> IMUConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sb_msgs::IMU_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sb_msgs::IMU_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sb_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sb_msgs': ['/home/dulluhan/Desktop/ROS_GPS/src/sb_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sb_msgs::IMU_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sb_msgs::IMU_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sb_msgs::IMU_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sb_msgs::IMU_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sb_msgs::IMU_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sb_msgs::IMU_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sb_msgs::IMU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b80745dc30b0f0d1cf203fb334331734";
  }

  static const char* value(const ::sb_msgs::IMU_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb80745dc30b0f0d1ULL;
  static const uint64_t static_value2 = 0xcf203fb334331734ULL;
};

template<class ContainerAllocator>
struct DataType< ::sb_msgs::IMU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sb_msgs/IMU";
  }

  static const char* value(const ::sb_msgs::IMU_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sb_msgs::IMU_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 c_x\n\
int32 c_y\n\
int32 c_z\n\
\n\
int32 a_x\n\
int32 a_y\n\
int32 a_z\n\
\n\
int32 g_x\n\
int32 g_y\n\
int32 g_z\n\
";
  }

  static const char* value(const ::sb_msgs::IMU_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sb_msgs::IMU_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.c_x);
      stream.next(m.c_y);
      stream.next(m.c_z);
      stream.next(m.a_x);
      stream.next(m.a_y);
      stream.next(m.a_z);
      stream.next(m.g_x);
      stream.next(m.g_y);
      stream.next(m.g_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct IMU_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sb_msgs::IMU_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sb_msgs::IMU_<ContainerAllocator>& v)
  {
    s << indent << "c_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.c_x);
    s << indent << "c_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.c_y);
    s << indent << "c_z: ";
    Printer<int32_t>::stream(s, indent + "  ", v.c_z);
    s << indent << "a_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.a_x);
    s << indent << "a_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.a_y);
    s << indent << "a_z: ";
    Printer<int32_t>::stream(s, indent + "  ", v.a_z);
    s << indent << "g_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.g_x);
    s << indent << "g_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.g_y);
    s << indent << "g_z: ";
    Printer<int32_t>::stream(s, indent + "  ", v.g_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SB_MSGS_MESSAGE_IMU_H
