// Generated by gencpp from file sb_msgs/Pose.msg
// DO NOT EDIT!


#ifndef SB_MSGS_MESSAGE_POSE_H
#define SB_MSGS_MESSAGE_POSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sb_msgs
{
template <class ContainerAllocator>
struct Pose_
{
  typedef Pose_<ContainerAllocator> Type;

  Pose_()
    : xpos(0.0)
    , ypos(0.0)
    , zpos(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
    }
  Pose_(const ContainerAllocator& _alloc)
    : xpos(0.0)
    , ypos(0.0)
    , zpos(0.0)
    , roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
    }



   typedef double _xpos_type;
  _xpos_type xpos;

   typedef double _ypos_type;
  _ypos_type ypos;

   typedef double _zpos_type;
  _zpos_type zpos;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;




  typedef boost::shared_ptr< ::sb_msgs::Pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sb_msgs::Pose_<ContainerAllocator> const> ConstPtr;

}; // struct Pose_

typedef ::sb_msgs::Pose_<std::allocator<void> > Pose;

typedef boost::shared_ptr< ::sb_msgs::Pose > PosePtr;
typedef boost::shared_ptr< ::sb_msgs::Pose const> PoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sb_msgs::Pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sb_msgs::Pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sb_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sb_msgs': ['/home/dulluhan/Desktop/ROS_GPS/src/sb_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sb_msgs::Pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sb_msgs::Pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sb_msgs::Pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sb_msgs::Pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sb_msgs::Pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sb_msgs::Pose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sb_msgs::Pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ee08947271b4f230fb2d5bc945eb424";
  }

  static const char* value(const ::sb_msgs::Pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ee08947271b4f23ULL;
  static const uint64_t static_value2 = 0x0fb2d5bc945eb424ULL;
};

template<class ContainerAllocator>
struct DataType< ::sb_msgs::Pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sb_msgs/Pose";
  }

  static const char* value(const ::sb_msgs::Pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sb_msgs::Pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 xpos\n\
float64 ypos\n\
float64 zpos\n\
\n\
float64 roll\n\
float64 pitch\n\
float64 yaw\n\
";
  }

  static const char* value(const ::sb_msgs::Pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sb_msgs::Pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.xpos);
      stream.next(m.ypos);
      stream.next(m.zpos);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sb_msgs::Pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sb_msgs::Pose_<ContainerAllocator>& v)
  {
    s << indent << "xpos: ";
    Printer<double>::stream(s, indent + "  ", v.xpos);
    s << indent << "ypos: ";
    Printer<double>::stream(s, indent + "  ", v.ypos);
    s << indent << "zpos: ";
    Printer<double>::stream(s, indent + "  ", v.zpos);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SB_MSGS_MESSAGE_POSE_H
