(cl:in-package sb_msgs-msg)
(cl:export '(LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
          POSITION_ACCURACY-VAL
          POSITION_ACCURACY
          HEADING-VAL
          HEADING
          SPEED-VAL
          SPEED
          ANGULAR_RATE-VAL
          ANGULAR_RATE
          GPS_TIME-VAL
          GPS_TIME
          POSITION_VALID-VAL
          POSITION_VALID
          HEADING_VALID-VAL
          HEADING_VALID
          SPEED_VALID-VAL
          SPEED_VALID
          ANGULAR_RATE_VALID-VAL
          ANGULAR_RATE_VALID
          WAYPOINT_LIST_VALID-VAL
          WAYPOINT_LIST_VALID
          ACTIVE_WAYPOINT_ID-VAL
          ACTIVE_WAYPOINT_ID
          WAYPOINT_ID-VAL
          WAYPOINT_ID
          WAYPOINT_PREVIOUS_ID-VAL
          WAYPOINT_PREVIOUS_ID
          WAYPOINT_NEXT_ID-VAL
          WAYPOINT_NEXT_ID
          WAYPOINT_X-VAL
          WAYPOINT_X
          WAYPOINT_Y-VAL
          WAYPOINT_Y
))